server:
  port: 8085
  
endpoints:
  beans:
    sensitive: false
  mappings:
    sensitive: false

spring:
  application:
    name: flashcard-app
  datasource:
    platform: oracle
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: BEARS
    password: p4ssw0rd
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database: ORACLE
    show-sql: true